development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: ideaportal_development
  pool: 5
  username: achal
  password: nandyelliidli
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: ideaportal_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  username: achal
  password: nandyelliidli
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: ideaportal_production
  pool: 5
  username: achal
  password: nandyelliidli
  host: localhost
